### ISSUE TITLE
qiime2 error 

### ISSUE THREAD

**Issue by hvanderheyden** [duceppemo/QIIME2_ITS#2]
**Command line:** 
conda activate qiime2-2021.11
python qiime2_its.py -q qiime2-2021.11 -i /media/herve/DATA1/Cimdec_Phytophthora/plate_test/fastq_files -o /media/herve/DATA1/Cimdec_Phytophthora/plate_test/output -m /media/herve/DATA1/Cimdec_Phytophthora/metadata2_test.tsv -c /home/herve/QIIME2_ITS/db/UNITE/unite-ver8-99-classifier-all.qza -t 6 -p 4 -se --extract-its1 --taxa Oomycota

**Error:** 
There was a problem importing /media/herve/DATA1/Cimdec_Phytophthora/plate_test/output/ITSxpress:

  /media/herve/DATA1/Cimdec_Phytophthora/plate_test/output/ITSxpress/B1_9_L001_R1_001.fastq.gz is not a(n) FastqGzFormat file:

  Missing sequence for record beginning on line 158009

Saved Visualization to: /media/herve/DATA1/Cimdec_Phytophthora/plate_test/output/demux-seqs.qzv
	Denoising data with DADA2...
Plugin error from dada2:

  No reads passed the filter. trunc_len (0) may be longer than read lengths, or other arguments (such as max_ee or trunc_q) may be preventing reads from passing the filter.

Debug info has been saved to /tmp/qiime2-q2cli-err-bqbizohh.log
There was an issue with loading the file /media/herve/DATA1/Cimdec_Phytophthora/plate_test/output/stats.qza as metadata:

  Metadata file path doesn't exist, or the path points to something other than a file. Please check that the path exists, has read permissions, and points to a regular file (not a directory): /media/herve/DATA1/Cimdec_Phytophthora/plate_test/output/stats.qza

  There may be more errors present in the metadata file. To get a full report, sample/feature metadata files can be validated with Keemei: https://keemei.qiime2.org

  Find details on QIIME 2 metadata requirements here: https://docs.qiime2.org/2021.11/tutorials/metadata/

**Comment by duceppemo** [comment]
I think this error was caused by running the pipeline from the repo folder and not calling the `qimme2_its.py` using the script full path. I'll investigate and modify the script accordingly so it can find the accessory script.

**Comment by duceppemo** [comment]
script modified to find the accessory script.
